### ISSUE TITLE
visualize the result

### ISSUE THREAD

**Issue by pradeepkc11** [ControlNet/LAV-DF#15]
I am able to run the evaluate.py file with given checkpoint value.After this it created a output folder which contains the result folder 
with .csv files. can you please tell me how to use this files to get the output in Videos

**Comment by ControlNet** [comment]
Hi, the output folder contains the boundary map output for each video file. So each csv file is the inference results of corresponding video. The columns in the CSV is `start`, `end` and `score`. In evaluate.py, after they're generated, the soft non-maximumm suppression is applied to these CSV files and generate an aggregated JSON file located in `outputs/results`, which can be used for calculate the metrics.

**Comment by pradeepkc11** [comment]
which script can be used to predict the fake or real for unseen video data, because their is no trained model is available to use it.
I wanted to test the model on unseen data to know if it works for it and also which python script should i use to predict the unseen data

**Comment by ControlNet** [comment]
Currently, the unseen video visualizations are not implemented, but it's easy to achieve. I suggest loading the CSV file, apply soft nms using `post_process.soft_nms` and then visualized by yourself.

**Comment by pradeepkc11** [comment]
ok thanks for the response and guidance
