### ISSUE TITLE
help,where is the metadata.min.json

### ISSUE THREAD

**Issue by garlic1234567** [ControlNet/LAV-DF#18]
first,thank you for your wonderful work.
when i run the train.py i met a problem:[Errno 2] No such file or directory: 'E:\\LAV-DF\\LAV-DF\\metadata.min.json'.
i dont understand about renaming the metadata.json to metadata.min.json. because i cant find metadata.json too.
@i-am-shreya @ControlNet 
please tell me how to fix it.

**Comment by ControlNet** [comment]
Hi @garlic1234567 , could you please display the file structure of the LAV-DF dataset?

**Comment by garlic1234567** [comment]
thank you for your reply. i made some mistakes and already figure it out.

but the datasets is too big for me to train. how should i pick the subset of it?
and how to generate the corresponding metadata.min.json.

thanks again. @ControlNet

**Comment by ControlNet** [comment]
Hi @garlic1234567 , all the experiments are reported based on fullset and a "subset" which exclude the samples which only the audio modality is modified. You can easily filter it based in the information from metadata.

For the metadata.min.json, I'm sorry for the misleading information, please just rename it.

**Comment by ControlNet** [comment]
Hi @garlic1234567 , I added the code automatically generate this file in https://github.com/ControlNet/LAV-DF/commit/7d84e6d0d93856ccde6ec10e5d7f275ebb368049. Not really tested it, but I think it should work.

**Comment by garlic1234567** [comment]
thanks for your kind reply, that really helps me a lot. Wish you the best.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ControlNet/LAV-DF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月28日(星期四) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ControlNet/LAV-DF] help,where is the metadata.min.json (Issue #18)





 
Hi @garlic1234567 , I added the code automatically generate this file in 7d84e6d. Not really tested it, but I think it should work.
