### ISSUE TITLE
How many epochs did you train?

### ISSUE THREAD

**Issue by liushenme** [ControlNet/LAV-DF#2]
Hi,

Your work is very interesting. I am rebuliding your model and I found the training is time-consuming for me using one 3090 GPU. So I want to know the number of gpus you used and the actual epochs when to stop training.

Thank you.

**Comment by ControlNet** [comment]
Hi,

I think one 3090 is sufficient to train this model. I trained it using 3090 with 16 precision, 4 batch size and 120 hours.

**Comment by liushenme** [comment]
Thanks for your reply.
