### ISSUE TITLE
Find a wrong

### ISSUE THREAD

**Issue by garfield5200** [ControlNet/LAV-DF#20]
Thank you for your excellent work！I see you made some changes to the file yesterday，but there's a mistake with that. In the file of “utils”，in 231 lines，you should add “  del meta[“transcript”]  ,   metadata_min.append(meta)  ”，then you can get a right metadata.min.json. Otherwise, the metadata.min.json will be null.

**Comment by ControlNet** [comment]
Thank you for pointing out this. Sorry for the mistake. Now it's fixed https://github.com/ControlNet/LAV-DF/commit/c864d1e4cd18351989715fb7ad2c61e041a66582.
