### ISSUE TITLE
Testing LAV-DF metadata.min.json

### ISSUE THREAD

**Issue by senemaktas** [ControlNet/LAV-DF#9]
Hello , I have several forged face video. And I would like to test them on LAVDF. 

**Can i run this without audio file ?**

 And When I give video path , it gives "LAVDF\LAV-DF\utils.py", line 16, in read_json
    **with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './db/metadata.min.json' " error.** 

**What is "metadata.min.json", how to create one?** 

Thanks for your work.

**Comment by ControlNet** [comment]
> Can i run this without audio file ?

Yes you can, but not directly. Please modify the code and use the visual boundary map output.

> What is "metadata.min.json", how to create one?

`metadata.min.json` is `metadata.json` without word level timestamps. You can directly use `metadata.json` by renaming to `metadata.min.json`.

**Comment by senemaktas** [comment]
Thanks for your respond, I see it now.

**Comment by garlic1234567** [comment]
hello,i met the same problem too, could you please tell me how to fix it by use metadata.json. cause i cant find metadata.json too.
